version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: list-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: notasdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - todo-net

  backend:
    build:
      context: ./backend
    container_name: list-backend
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:123@postgres:5432/notasdb"
      SECRET_KEY: "supersecretkey"
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - todo-net

  frontend:
    build:
      context: ./frontend
    container_name: list-frontend
    depends_on:
      - backend
    networks:
      - todo-net

  nginx:
    image: nginx:alpine
    container_name: list-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - todo-net

volumes:
  db_data:

networks:
  todo-net:
    driver: bridge
