version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: db-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: notasdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5643:5643"
    networks:
      - todo-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: lista-backend
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:123@postgres:5432/notasdb"
      SECRET_KEY: "supersecretkey"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - todo-net

volumes:
  db_data:

networks:
  todo-net:
    driver: bridge
