
services:
  postgres:
    image: postgres:15-alpine
    container_name: db-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: notasdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5643:5643"
    networks:
      - todo-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: list-backend
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:123@postgres:5432/notasdb"
      SECRET_KEY: "supersecretkey"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - todo-net

  frontend:
    build: ./frontend    
    container_name: list-frontend
    #ports:
      #- "80:80"
    #volumes:
      # Montagem dos arquivos estáticos do frontend no nginx
      #- ./frontend:/usr/share/nginx/html
      # Configuração do nginx
      #- ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - postgres
    networks:
      - todo-net

  nginx:
    image: nginx:alpine
    container_name: list-nginx
    ports:
      - "80:80"
    volumes:
      # Montagem dos arquivos estáticos do frontend
      - ./frontend:/usr/share/nginx/html
      # Configuração do nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      
    depends_on:
      - backend
      
    networks:
      - todo-net

volumes:
  db_data:

networks:
  todo-net:
    driver: bridge
