version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - todo-net

  backend1:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend1
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/todo_db
    depends_on:
      - db
    networks:
      - todo-net

  backend2:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend2
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/todo_db
    depends_on:
      - db
    networks:
      - todo-net

  backend3:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend3
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/todo_db
    depends_on:
      - db
    networks:
      - todo-net

  nginx:
    image: nginx:stable
    container_name: proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - todo-net

volumes:
  db_data:

networks:
  todo-net:
    driver: bridge
